let myDate = new Date()
// console.log(myDate)
// console.log(myDate.toString())
// console.log(myDate.toDateString())
// console.log(myDate.toISOString())
// console.log(myDate.toLocaleDateString())
// console.log(myDate.toLocaleString())
// console.log(myDate.toLocaleTimeString())
// console.log(myDate.toTimeString())
//console.log(myDate.toUTCString())
// console.log(myDate.toJSON())
// let myCreatedDate = new Date(2026,5,27,)
let myCreatedDate = new Date(2026,5,27,12,8,0)
console.log(myCreatedDate.toLocaleString());

